language: generic
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

addons:
  ssh_known_hosts: 142.93.227.119

before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa

script:
  - "true"

after_success:
  - docker build -t halldorvil/blog-client:latest -t halldorvil/blog-client:$SHA ./client
  - docker build -t halldorvil/blog-api:latest -t halldorvil/blog-api:$SHA ./api

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push halldorvil/blog-client:latest
  - docker push halldorvil/blog-api:latest

  - docker push halldorvil/blog-client:$SHA
  - docker push halldorvil/blog-api:$SHA

  - bash ./deploy.sh
