language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t halldorvil/blog -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true halldorvil/blog npm test -- --coverage

after_success:
    - docker build -t halldorvil/blog-client ./client
    - docker build -t halldorvil/blog-nginx ./nginx
    - docker build -t halldorvil/blog-server ./server

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push halldorvil/blog-client
    - docker push halldorvil/blog-nginx
    - docker push halldorvil/blog-server