version: "3"

services:
  nginx:
    restart: unless-stopped
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/dev:/etc/nginx/conf.d
    depends_on:
      - client
      - api
        
  postgres:
    restart: unless-stopped
    image: postgres:13.2-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

  api:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
      - PORT=5000
    depends_on:
      - postgres

  client:
    restart: unless-stopped
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
