version: "3"
services:
  nginx:
    restart: always
    image: halldorvil/blog-nginx:TAG
    ports:
      - 80:80
    depends_on:
      - api
      - client
  api:
    restart: always
    image: halldorvil/blog-server:TAG
  client:
    restart: always
    stdin_open: true
    image: halldorvil/blog-client:TAG
    environment:
      - BLOG_URL=http://localhost:3050/api/blog
