version: "3"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
      - client
  
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
  
  client:
    restart: always
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./static
      o: bind
