version: "3"

services:
  nginx:
    restart: unless-stopped
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/dev:/etc/nginx/conf.d
    depends_on:
      - client
      - api

  api:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: ./server

  client:
    restart: unless-stopped
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
